[package]
name = "hard_volume"
version = "0.1.0"
authors = ["Rainymy <48211766+Rainymy@users.noreply.github.com>"]
edition = "2021"
license = "MIT"

[[bin]]
name = "hard_volume"
test = false
bench = false

[dependencies]
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0.0"
embedded-time = "0.12.1"
embedded-graphics = "0.8.2"
ssd1306 = { version = "0.10.0" }
heapless = { version = "0.9.3", features = ["ufmt"] }
avr-device = "0.8.1"
fugit = "0.4.0"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e5c8f37fe48419956e722490a82b9ca9b9fc61a2"
features = ["arduino-uno", "rt", "board-selected", "mcu-atmega"]

# [dependencies.atmega-hal]
# git = "https://github.com/rahix/avr-hal"
# rev = "e5c8f37fe48419956e722490a82b9ca9b9fc61a2"
# features = ["atmega328p", "rt"]

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"
codegen-units = 1

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
